---
title: Empirical Spirits
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
url: https://www.empiricalspirits.co
baseurl: 
description: Empirical Spirits. A Copenhagen-based distillery and fermentation workshop.
  On a constant search for flavor.
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Empirical Spirits
email: info@empiricalspirits.co
google_site_verification: 
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%Y"
future: true
social:
  instagram: 
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
imgix:
  source: https://empirical-spirits.imgix.net